---
# handlers file for deploy_rhcsa_server
- name: Restart nfs
  ansible.builtin.systemd:
    name: nfs-server.service
    state: restarted
    enabled: true
  listen: restart_nfs

- name: Restart firewalld
  ansible.builtin.systemd:
    name: firewalld.service
    state: restarted
    enabled: true
  listen: restart_firewalld

- name: Restart chrony
  ansible.builtin.systemd:
    name: chronyd.service
    state: restarted
    enabled: true
  listen: restart_chrony

...
