- name: Deploy Configurations for the Client Server
  hosts: rhcsa_client
  gather_facts: true
  become: true
  tasks:

    - name: Include the deploy_rhcsa_client role
      ansible.builtin.include_role:
        name: deploy_rhcsa_client
      when: inventory_hostname in groups['rhcsa_client']

...
