- name: Deploy Configurations for the NFS server
  hosts: rhcsa_server
  gather_facts: true
  become: true
  tasks:

    - name: Include the deploy_rhcsa_server role
      ansible.builtin.include_role:
        name: deploy_rhcsa_server
      when: inventory_hostname in groups['rhcsa_server']


