---
- name: Deploy an Azure Workgroup Environment
  hosts: all
# connection: local
  gather_facts: false
  environment:
    # AZURE_TENANT: "{{ lookup('env','AZURE_TENANT') }}"
    # AZURE_CLIENT_ID: "{{ lookup('env','AZURE_CLIENT_ID') }}"
    # AZURE_SECRET: "{{ lookup('env','AZURE_SECRET') }}"
    # AZURE_SUBSCRIPTION_ID: "{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}"
    ANSIBLE_AZURE_AUTH_SOURCE: env
  tasks:
    - name: Slurp the student user public key
      ansible.builtin.slurp:
        src: /home/student/.ssh/id_rsa.pub
      register: student_public_key
      when: inventory_hostname in groups['rhcsa_client']

    - name: se
    - set_fact:
        rhcsa2_public_key: "{{ hostvars['rhcsa-vm-1']['student_public_key']['content']|b64decode }}"

    - debug:
        var: rhcsa2_public_key


    - name: debug stuff
      ansible.builtin.debug:
        #var: lookup('vars', "hostvars['rhcsa-vm-1']['student_public_key']['content']|b64decode")
        var: lookup('vars', 'rhcsa2_public_key')
      run_once: true


...
