---
plugin: azure.azcollection.azure_rm
plain_host_names: true

conditional_groups:
  rhcsa_server: tags['server_type'] == "rhcsa_server"
  rhcsa_client: tags['server_type'] == "rhcsa_client"
  rhcsa_reposerver: tags['server_type'] == "rhcsa_reposerver"
  rhcsa_generic: tags['server_type'] == "rhcsa_generic"
  lab_core: "'generic' not in tags['server_type']"
  


hostvar_expressions:
  ansible_user: "'student'"
  ansible_ssh_private_key_file: "'~/.ssh/id_rsa_rhpds'"
  ansible_host: public_ipv4_addresses|first

keyed_groups:
- prefix: workgroup
  key: tags['server_type']

...