---
plugin: azure.azcollection.azure_rm
plain_host_names: true

conditional_groups:
  rhcsa_client: tags['server_type'] == "rhcsa_client"
  rhcsa_reposerver: tags['server_type'] == "rhcsa_reposerver"
  control_servers: "'control' in tags['server_type']"
  rhcsa_control: tags['server_type'] == "rhcsa_control"
  rhcsa_node: tags['server_type'] == "rhcsa_node"

hostvar_expressions:
  ansible_user: "'student'"
  ansible_ssh_private_key_file: "'~/.ssh/id_rsa_rhpds'"
  ansible_host: public_ipv4_addresses|first

keyed_groups:
- prefix: workgroup
  key: tags['server_type']

...