---
# defaults file for deploy_rhcsa_client
filelist:
  - .profile
  - .bash_profile
  - .bashrc
  - .bash_logout

larry_dirs:
  - path: /usr/local/etc
    size: '10M'
    suffix: txt
  - path: /usr/lib/locale
    size: '5M'
    suffix: lib
  - path: /etc
    size: '3M'
    suffix: log

nfs_users:
  - name: larry
    uid: '1002'
  - name: moe
    uid: '1003'
  - name: curly
    uid: '1004'

opt_test_dirs:
  - name: test1
    suffix: txt
  - name: test2
    suffix: log
  - name: test3
    suffix: out

random_string: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=10) }}"
