- name: Deploy Configurations
  hosts: rhcsa_reposerver
  gather_facts: true
  become: true
  tasks:

    - name: Include the deploy_rhcsa_reposerver role
      ansible.builtin.include_role:
        name: deploy_rhcsa_reposerver
      when: inventory_hostname in groups['rhcsa_reposerver']

