---
# handlers file for deploy_rhcsa_reposerver
- name: restart_httpd
  ansible.builtin.systemd:
    service: httpd
    state: restarted
    enabled: true

- name: restart_firewalld
  ansible.builtin.systemd:
    service: firewalld
    state: restarted
    enabled: true

...
