---
# handlers file for deploy_rhcsa_reposerver
- name: Restart_httpd
  ansible.builtin.systemd:
    service: httpd
    state: restarted
    enabled: true

- name: Restart_firewalld
  ansible.builtin.systemd:
    service: firewalld
    state: restarted
    enabled: true

- name: restart mkdocs
  ansible.builtin.systemd:
    service: mkdocs
    state: started
    enabled: true
...

