---
# handlers file for deploy_rhcsa_reposerver
- name: Restart httpd
  ansible.builtin.systemd:
    service: httpd
    state: restarted
    enabled: true
  listen: restart_httpd

- name: Restart firewalld
  ansible.builtin.systemd:
    service: firewalld
    state: restarted
    enabled: true
  listen: restart_firewalld

- name: Restart mkdocs
  ansible.builtin.systemd:
    name: mkdocs.service
    state: restarted
    enabled: yes
    scope: user
  become_user: student
  environment:
    XDG_RUNTIME_DIR: "/run/user/student"
  listen: restart_mkdocs

...

