---
# tasks file for deploy_rhcsa_reposerver
- name: Create /mnt/repos directory
  ansible.builtin.file:
    path: /mnt/repos
    state: directory
    mode: 0755
    owner: root
    group: root
    setype: httpd_sys_content_t

- name: Install httpd to serve RHEL Repos
  ansible.builtin.dnf:
    name:
      - httpd
    state: present
  retries: 5
  delay: 20
  notify:
    - restart_httpd

- name: Permit traffic in default zone for http service
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true
  notify:
    - restart_firewalld

- name: Create a symlink from /var/www/html/repos to /mnt/repos
  ansible.builtin.file:
    src: /mnt/repos
    dest: /var/www/html/repos
    owner: root
    group: root
    state: link

- name: Create at job to sync the repos
  ansible.posix.at:
    command: reposync -q -p /mnt/repos/{{ repo['name'] }} --download-metadata --norepopath --repoid={{ repo['repoid'] }}
    count: 2
    units: minutes
  loop: "{{ reposync_repos }}"
  loop_control:
    loop_var: repo

- name: Create at job to do a dnf update in 20 minutes so reposync can complete first
  ansible.posix.at:
    command: dnf update -y
    count: 20
    units: minutes

- name: Install an sshd config for users with password allowed
  ansible.builtin.template:
    src: '02-shemp.conf.j2'
    dest: /etc/ssh/sshd_config.d/02-shemp.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd

...
