---
# tasks file for deploy_rhcsa_reposerver
- name: Install httpd to serve RHEL Repos
  ansible.builtin.dnf:
    name: httpd
    state: present
  notify: Restart firewalld

- name: Permit traffic in default zone for madness port
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ reposerver_fw_port }}"
  notify:
    - restart_firewalld

- name: Permit traffic in default zone for http service
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ reposerver_fw_svc }}"
  notify:
    - restart_firewalld

- name: Change contexts for repos
  community.general.sefcontext:
    target: '/mnt/repos(/.*)?'
    setype: httpd_sys_content_t
    state: present
  register: __repo_context

- name: Run restorecon on /mnt/repos
  ansible.builtin.shell: |
    restorecon -R /mnt/repos
  changed_when: false
  when: __repo_context is changed

- name: Create a symlink from /var/www/html/repos to /mnt/repos
  ansible.builtin.file:
    src: /mnt/repos
    dest: /var/www/html/repos
    owner: root
    group: root
    state: link

- name: Create a logical volume of 5G
  community.general.lvol:
    vg: rootvg
    lv: madnesslv
    size: 5G

- name: Create the filesystem for the madness logical volume
  community.general.filesystem:
    fstype: xfs
    dev: /dev/rootvg/madnesslv

- name: Mount filesystem
  ansible.posix.mount:
    path: /docs
    src: /dev/rootvg/madnesslv
    fstype: xfs
    state: mounted

- name: Install Madness for markdown docs
  containers.podman.podman_image:
    name: docker.io/dannyben/madness

- name: Running httpd image.
  containers.podman.podman_container:
    name: madness
    image: docker.io/dannyben/madness
    volume: 
      - /docs
    state: started
    command: server
    ports: 3000:3000

...
